apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-pod-reader
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: pod-reader-sa
    namespace: self-hosted-runners
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
